/*Copyright (c) 2023-2024 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.healthconnect_pro.health_connect.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class UpdateAppointTimingsVariableRequest implements Serializable {


    @JsonProperty("date2")
    @NotNull
    private Date date2;

    @JsonProperty("select1")
    @NotNull
    private String select1;

    @JsonProperty("id")
    @NotNull
    private Integer id;

    public Date getDate2() {
        return this.date2;
    }

    public void setDate2(Date date2) {
        this.date2 = date2;
    }

    public String getSelect1() {
        return this.select1;
    }

    public void setSelect1(String select1) {
        this.select1 = select1;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UpdateAppointTimingsVariableRequest)) return false;
        final UpdateAppointTimingsVariableRequest updateAppointTimingsVariableRequest = (UpdateAppointTimingsVariableRequest) o;
        return Objects.equals(getDate2(), updateAppointTimingsVariableRequest.getDate2()) &&
                Objects.equals(getSelect1(), updateAppointTimingsVariableRequest.getSelect1()) &&
                Objects.equals(getId(), updateAppointTimingsVariableRequest.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getDate2(),
                getSelect1(),
                getId());
    }
}