/*Copyright (c) 2023-2024 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.healthconnect_pro.health_connect.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.commons.wrapper.IntegerWrapper;
import com.wavemaker.runtime.commons.file.manager.ExportedFileManager;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;

import com.healthconnect_pro.health_connect.models.query.UpdateAppointTimingsVariableRequest;
import com.healthconnect_pro.health_connect.service.Health_connectQueryExecutorService;

@RestController(value = "Health_connect.QueryExecutionController")
@RequestMapping("/health_connect/queryExecutor")
@Api(value = "QueryExecutionController", description = "controller class for query execution")
public class QueryExecutionController {

    private static final Logger LOGGER = LoggerFactory.getLogger(QueryExecutionController.class);

    @Autowired
    private Health_connectQueryExecutorService queryService;

    @Autowired
	private ExportedFileManager exportedFileManager;

    @PutMapping(value = "/queries/updateAppointTimingsVariable")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "updateAppointTimingsVariable")
    public IntegerWrapper executeUpdateAppointTimingsVariable(@Valid @RequestBody UpdateAppointTimingsVariableRequest updateAppointTimingsVariableRequest, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: updateAppointTimingsVariable");
        Integer _result = queryService.executeUpdateAppointTimingsVariable(updateAppointTimingsVariableRequest);
        LOGGER.debug("got the result for named query: updateAppointTimingsVariable, result:{}", _result);
        return new IntegerWrapper(_result);
    }

}