/*Copyright (c) 2023-2024 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.healthconnect_pro.health_connect;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Hospitals generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`hospitals`")
public class Hospitals implements Serializable {

    private Integer id;
    private String hospitalName;
    private String hospitalAddress;
    private String hospitalDescription;
    private String picture;
    private Integer numberofdoctors;
    private Integer numberofnurses;
    private Integer personalstaff;
    private String city;
    private String hospitalState;
    private String zipCode;
    private String country;
    private String phoneNumber;
    private String email;
    private String website;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`hospital_name`", nullable = true, length = 255)
    public String getHospitalName() {
        return this.hospitalName;
    }

    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName;
    }

    @Column(name = "`hospital_address`", nullable = true, length = 255)
    public String getHospitalAddress() {
        return this.hospitalAddress;
    }

    public void setHospitalAddress(String hospitalAddress) {
        this.hospitalAddress = hospitalAddress;
    }

    @Column(name = "`hospital_description`", nullable = true, length = 255)
    public String getHospitalDescription() {
        return this.hospitalDescription;
    }

    public void setHospitalDescription(String hospitalDescription) {
        this.hospitalDescription = hospitalDescription;
    }

    @Column(name = "`picture`", nullable = true, length = 255)
    public String getPicture() {
        return this.picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }

    @Column(name = "`numberofdoctors`", nullable = true, scale = 0, precision = 10)
    public Integer getNumberofdoctors() {
        return this.numberofdoctors;
    }

    public void setNumberofdoctors(Integer numberofdoctors) {
        this.numberofdoctors = numberofdoctors;
    }

    @Column(name = "`numberofnurses`", nullable = true, scale = 0, precision = 10)
    public Integer getNumberofnurses() {
        return this.numberofnurses;
    }

    public void setNumberofnurses(Integer numberofnurses) {
        this.numberofnurses = numberofnurses;
    }

    @Column(name = "`personalstaff`", nullable = true, scale = 0, precision = 10)
    public Integer getPersonalstaff() {
        return this.personalstaff;
    }

    public void setPersonalstaff(Integer personalstaff) {
        this.personalstaff = personalstaff;
    }

    @Column(name = "`city`", nullable = true, length = 255)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Column(name = "`hospital_state`", nullable = true, length = 255)
    public String getHospitalState() {
        return this.hospitalState;
    }

    public void setHospitalState(String hospitalState) {
        this.hospitalState = hospitalState;
    }

    @Column(name = "`zip_code`", nullable = true, length = 255)
    public String getZipCode() {
        return this.zipCode;
    }

    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    @Column(name = "`country`", nullable = true, length = 255)
    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    @Column(name = "`phone_number`", nullable = true, length = 255)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @Column(name = "`email`", nullable = true, length = 255)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "`website`", nullable = true, length = 255)
    public String getWebsite() {
        return this.website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Hospitals)) return false;
        final Hospitals hospitals = (Hospitals) o;
        return Objects.equals(getId(), hospitals.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}