/*Copyright (c) 2023-2024 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.healthconnect_pro.health_connect;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Medications generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`Medications`")
public class Medications implements Serializable {

    private Integer id;
    private String medications;
    private String frequency;
    private String time;
    private String gender;
    private Integer age;
    private String enterYourDiagnosis;
    private String dosage;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`Medications`", nullable = true, length = 255)
    public String getMedications() {
        return this.medications;
    }

    public void setMedications(String medications) {
        this.medications = medications;
    }

    @Column(name = "`Frequency`", nullable = true, length = 255)
    public String getFrequency() {
        return this.frequency;
    }

    public void setFrequency(String frequency) {
        this.frequency = frequency;
    }

    @Column(name = "`Time`", nullable = true, length = 255)
    public String getTime() {
        return this.time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    @Column(name = "`gender`", nullable = true, length = 20)
    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    @Column(name = "`Age`", nullable = true, scale = 0, precision = 10)
    public Integer getAge() {
        return this.age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    @Column(name = "`Enter_Your_Diagnosis`", nullable = true, length = 255)
    public String getEnterYourDiagnosis() {
        return this.enterYourDiagnosis;
    }

    public void setEnterYourDiagnosis(String enterYourDiagnosis) {
        this.enterYourDiagnosis = enterYourDiagnosis;
    }

    @Column(name = "`dosage`", nullable = true, length = 255)
    public String getDosage() {
        return this.dosage;
    }

    public void setDosage(String dosage) {
        this.dosage = dosage;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Medications)) return false;
        final Medications medicationsInstance = (Medications) o;
        return Objects.equals(getId(), medicationsInstance.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}