/*Copyright (c) 2023-2024 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.healthconnect_pro.health_connect;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Symptoms generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`symptoms`")
public class Symptoms implements Serializable {

    private Integer id;
    private String symptom1;
    private String symptom2;
    private String symptom3;
    private String symptom4;
    private String symptom5;
    private String diagnosis;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`Symptom1`", nullable = true, length = 255)
    public String getSymptom1() {
        return this.symptom1;
    }

    public void setSymptom1(String symptom1) {
        this.symptom1 = symptom1;
    }

    @Column(name = "`Symptom2`", nullable = true, length = 255)
    public String getSymptom2() {
        return this.symptom2;
    }

    public void setSymptom2(String symptom2) {
        this.symptom2 = symptom2;
    }

    @Column(name = "`Symptom3`", nullable = true, length = 255)
    public String getSymptom3() {
        return this.symptom3;
    }

    public void setSymptom3(String symptom3) {
        this.symptom3 = symptom3;
    }

    @Column(name = "`Symptom4`", nullable = true, length = 255)
    public String getSymptom4() {
        return this.symptom4;
    }

    public void setSymptom4(String symptom4) {
        this.symptom4 = symptom4;
    }

    @Column(name = "`Symptom5`", nullable = true, length = 255)
    public String getSymptom5() {
        return this.symptom5;
    }

    public void setSymptom5(String symptom5) {
        this.symptom5 = symptom5;
    }

    @Column(name = "`Diagnosis`", nullable = true, length = 255)
    public String getDiagnosis() {
        return this.diagnosis;
    }

    public void setDiagnosis(String diagnosis) {
        this.diagnosis = diagnosis;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Symptoms)) return false;
        final Symptoms symptoms = (Symptoms) o;
        return Objects.equals(getId(), symptoms.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}